# Generated by Django 4.2 on 2023-05-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='b_date',
            field=models.DateField(null=True),
        ),
    ]
