# Generated by Django 4.2 on 2023-05-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclmain', '0002_alter_student_b_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolName', models.CharField(max_length=100, null=True)),
                ('subjectCount', models.IntegerField(null=True)),
                ('studentCount', models.IntegerField(null=True)),
                ('teachersCount', models.IntegerField(null=True)),
                ('labsCount', models.IntegerField(null=True)),
                ('latestHeading', models.CharField(max_length=100, null=True)),
                ('feature1', models.CharField(max_length=100, null=True)),
                ('feature2', models.CharField(max_length=100, null=True)),
                ('feature3', models.CharField(max_length=100, null=True)),
                ('latestDescription1', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
