# Generated by Django 4.2 on 2023-05-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclmain', '0004_schooldetails_latestdescription2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
