# Generated by Django 4.2 on 2023-05-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sclmain', '0005_student_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='mark1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sclmain.marks'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=50, null=True),
        ),
    ]
