# Generated by Django 4.2 on 2023-05-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclmain', '0009_alter_marks_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('facebookLink', models.CharField(max_length=1000)),
                ('twitterLink', models.CharField(max_length=1000)),
                ('googlePlus', models.CharField(max_length=1000)),
                ('linkedInLink', models.CharField(max_length=1000)),
                ('youtubeLink', models.CharField(max_length=1000)),
                ('addressLine1', models.CharField(max_length=100)),
                ('addressLine2', models.CharField(max_length=100)),
                ('addressLine3', models.CharField(max_length=100)),
                ('websiteLink', models.CharField(max_length=1000)),
            ],
        ),
    ]
