# Generated by Django 4.2 on 2023-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclmain', '0010_contactdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetails',
            name='latestImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
